### ISSUE TITLE
Missing getting start documentation

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#107]
**Describe the bug**
If I am new to the project I can not easily understand how to get started.

**To Reproduce**
1. Go to the readme
2. See lack of information

**What version of Mailchain are you using ?**
N/A

**Expected behavior**
A clear and concise description of what you to do to get started

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by tboeckmann** [comment]
Fixed: go to docs.mailchain.xyz
