### ISSUE TITLE
Accept message header field: content-type to support HTML & plain text

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#112]
**Is your feature request related to a problem? Please describe.**
I want to send html-based messages so I can format messages and include pictures 

**Describe the solution you'd like**
The application may use a `Content-Type: multipart/alternative` be able to include message parts:
* `text/html`
* `text/plain`

**Describe alternatives you've considered**
Sending the message with ascii art or attaching pictures to the message. Neither work particularly well.

**Additional context**
See https://tools.ietf.org/html/rfc1521#section-7.2 for multipart detail

**Comment by robdefeo** [comment]
There appears to be a simpler solution to this issue for the html emails lets scope this down to be able to encode and accept `Content-Type: text/html` and continue to use `quoted-printable` as the encoding.
Currently https://github.com/mailchain/mailchain/blob/d89f8eb7e82ae788aea5c56f3763cc3b05e8cb8f/internal/mail/rfc2822/message.go the encoding is hardcoded as 
```
	headers += "Content-Type: text/plain; charset=\"UTF-8\"\r\n"
	headers += "Content-Transfer-Encoding: quoted-printable\r\n"
```

This should instead accept a `content-type` which is checked for either or `Content-Type: text/plain; charset=\"UTF-8\"` or `Content-Type: text/html; charset=\"UTF-8\"` this is then placed in the content-type header.
