### ISSUE TITLE
Public key lookup service

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#125]
**Is your feature request related to a problem? Please describe.**
Create a service that allows looking up a public key by address

**Describe the solution you'd like**
Currently Etherscan is the only solution to lookup public key by address.

**Describe alternatives you've considered**
- Proxy calls to etherscan
- Custom solution for mailchain

**Additional context**
Ref #118

**Comment by Despire** [comment]
This looks like an interesting issue!
Is anybody working on it ? If not can i be assigned ?

**Comment by robdefeo** [comment]
Hi @Despire thanks for expressing interest in this, sorry it slipped through the gaps. Other than having an alternative to etherscan, the big reason is to have control of returning the correct response when only being interested in mailchain messages not all transactions. Yes it would be implemented as another command e.g. `pubkey-lookup` or similar name.  To implement it it would be required that the `cmd/indexer` is completed. However this can be started and the API interface and presentation functionality defined. Is this something you are still interested in picking up? If so I'll create some sub tasks.

**Comment by Despire** [comment]
Hi @robdefeo yes I'm still interested.

**Comment by robdefeo** [comment]
@Despire excellent, since this is a large issue lets use this issue as an epic. I have created a project board for [`cmd/pkf`](https://github.com/orgs/mailchain/projects/8) where you can see the sub tasks I will start populating it. Feel free to pick any up or propose changes. Also worth being aware of [`cmd/indexer`](https://github.com/orgs/mailchain/projects/7) as this builds the public key index.
