### ISSUE TITLE
Messages by address service

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#126]
**Is your feature request related to a problem? Please describe.**
Currently Etherscan is the only solution to lookup transactions by address.

**Describe the solution you'd like**
Create a service that allows looking up mailchain messages by address.

**Describe alternatives you've considered**
- Proxy calls to etherscan
- Custom solution for mailchain

**Additional context**
ref #118

**Comment by tboeckmann** [comment]
@robdefeo Dupe of #161 ?

**Comment by robdefeo** [comment]
@tboeckmann #161 is about providing a better user experience by allowing user to main an address book and use friendly names. This #126 is to provide an address index for ethereum which does not exist, currently mailchain relies on etherscan for this.

**Comment by tboeckmann** [comment]
Sorry, I meant Address index service #251

**Comment by robdefeo** [comment]
@tboeckmann yes. I will close this in favor of #251. Good catch
