### ISSUE TITLE
Warning for log-level

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#134]
**Describe the bug**
When setting the log level, I receive the following error:

```
Invalid 'log-level' , default to [Warning]
```

**To Reproduce**

1. Run the mailchain application with any of the following:
    ```
    ./mailchain serve --log-level=debug
    ./mailchain serve --log-level debug
    ./mailchain serve --log-level=Debug
    ./mailchain serve --log-level Debug
    ```
4. See error: `WARN[0000] Invalid 'log-level' , default to [Warning]`

**What version of Mailchain are you using ?**
`Version: v0.0.2`

**Expected behavior**
It should accept the arguement with `--log-level debug` or `--log-level=debug`

**Desktop (please complete the following information):**
 - Mac, OS X 14.4

**Comment by robdefeo** [comment]
Also the `config` flag does not work
