### ISSUE TITLE
Add file extension to releases

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#147]
**Describe the bug**
When I download a file from https://github.com/mailchain/mailchain/releases/latest e.g. `mailchain-v0.0.5-macOS-64bit`, there is no file extension. How do I know what to do with this file?

**To Reproduce**
1. Go to https://github.com/mailchain/mailchain/releases/latest
2. Click on & download mailchain-v0.0.5-macOS-64bit

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.5`

**Expected behavior**
It should have `.zip` or `.tar.gz` or whatever is appropriate.

**Comment by tboeckmann** [comment]
I figured out this is now shipping as an executable.

Problems with this are:
* it requires approval in chrome to download `filename is not commonly downloaded and may be dangerous`
* it requires allowing in settings on a mac to `open anyway`
* it require changing to an executable (`chmod 700`)
* there is no license or README anymore

**Comment by robdefeo** [comment]
It was doing be this way, following the example used to make the run.mailchain.xyz/install.sh. considering the above problems, reverting to compressed format and extend the script to support that.

**Comment by robdefeo** [comment]
Install script updated and binaries created ref #148
