### ISSUE TITLE
Better Errors

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#149]
**Is your feature request related to a problem? Please describe.**
The application does not give informative error. For example, when I have an error and logging is set to debug, the following appears:
![image](https://user-images.githubusercontent.com/2022378/58133815-d1a9b780-7c1c-11e9-837e-be016e0762af.png)
 
**Describe the solution you'd like**
Display an error message to describe the problem

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by robdefeo** [comment]
closed by #149
