### ISSUE TITLE
Address book service

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#161]
**Is your feature request related to a problem? Please describe.**
Looking up addresses and copying and pasting across different screens is a bad user experience.

**Describe the solution you'd like**
I want to be able to:
* use friendly names for certain addresses
* store regularly used addresses
* be able to look up addresses from my address book
* use the same addresses for multiple supported chains and networks

The api should provide an endpoint for addresses (POST, PUT, GET, DELETE):

* GET: /address-book/addresses
    returns: `id` (int), `name` (string), `address` (string), `standard` (string)

    ```json
    [
      {
        "id": 33,
        "name": "Bob",
        "address": "0x000000000..."
      },
      {
     ...
      }
    ]
    ```

* GET: /address-book/addresses/{id}
    returns: `id` (int), `name` (string), `address` (string), `standard` (string)

    ```json
    {
      "id": 33,
      "name": "Bob",
      "address": "0x000000000...",
      "standard": "ethereum"
    }
    ```

* POST: /ethereum/address-book/addresses
    params: `name` (string), `address` (string), `standard` (string)

    ```json
    {
      "name": "Bob",
      "address": "0x000000000...",
      "standard": "ethereum"
    }
    ```

* PUT: /ethereum/address-book/addresses/{id}
    params: `name` (string), `address` (string), `standard` (string)

    ```json
    {
      "name": "Bob",
      "address": "0x111111111...",
      "standard": "ethereum"
    }
    ```

* DELETE: /ethereum/address-book/addresses/{id}

**Comment by robdefeo** [comment]
https://github.com/google/leveldb is the store used by default for state, this can be used to maintain an address book locally for the client.
