### ISSUE TITLE
A better way to handle Infura in the init and config

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#178]
**Is your feature request related to a problem? Please describe.**
A new user gets frustrated when user mistakenly adds the wrong infura URL to the init or config file.
For example, if user, in the `init`, selects a testnet (e.g. ropsten) and enters the endpoint:
`https://mainnet.infura.io/v3/{project_id}`
instead of:
`https://ropsten.infura.io/v3/{project_id}`
the user runs the risk of (a) sending a message on the wrongnet (b) spending wrongnet ETH (c) being very confused and needing to go digging through config files to troubleshoot.

**Describe the solution you'd like**
Because Infura uses the same project ID for each different network endpoint, the `init` and config file values should be the `project_id` only.
The init wizard should validate the 32 character string pattern for Infura project_ids.

Other derived benefits:

* This removes the need for the user to select the network in the `init` wizard and the client should support all infura networks out of the box.
* This makes it less likely that users have trouble getting up and running but can still use infura.

**Comment by robdefeo** [comment]
While the init method is no longer used this is still a valid issue

**Comment by robdefeo** [comment]
@tboeckmann the configuration is dealt with very differently now since the init command has been removed, I think this issue can be safely closed.
