### ISSUE TITLE
ResolveName Docs Misleading

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#235]
**Describe the bug**
When I follow the docs/example in the mailchain client (http://127.0.0.1:8080/api/docs#tag/ResolveName) to resolve a name, I enter the url `http://127.0.0.1:8080/api/nameservice/name/mailchain.eth/resolve`.

This returns the error:

```json
{"code":422,"message":"protocol must be specified exactly once"}
```

**To Reproduce**
1. Go to 'http://127.0.0.1:8080/api/nameservice/name/mailchain.eth/resolve'
2. See error

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.30`

**Expected behavior**

The command works with url params: `http://127.0.0.1:8080/api/nameservice/name/mailchain.eth/resolve?network=mainnet&protocol=ethereum`

to return:

`{"address":"0x........"}`

**Comment by robdefeo** [comment]
What are you expecting to see a different error message or different docs? `protocol` is a required field along with, `address`, `network`.
