### ISSUE TITLE
Create version end point

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#243]
**Is your feature request related to a problem? Please describe.**
When consuming the API there is no easy way to know what version of the client is being run.

**Describe the solution you'd like**
`/api/version` end point with the version of the client.

**Describe alternatives you've considered**
None

**Additional context**
This will allow dealing gracefully with older or non supported clients being run against new front ends.

**Comment by robdefeo** [comment]
sample response
```
{
  "version": "vxx.xx.xx",
  "commit": "xxxx",
  "time": "xxx":
}
```

**Comment by nikosk686** [comment]
Checking this out.

**Comment by robdefeo** [comment]
Big thanks @nikosk686 for your help for this :boom: it makes #110 possible and importantly allows the front end to tell the user that their client needs upgrading. This will be essential when we work on #244 and other breaking changes.
