### ISSUE TITLE
Coveralls is being too fusy and failing the build

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#268]
Slight drops in code coverage result in the build failing with coveralls, suggest to find a setting to prevent this or move to https://codecov.io/ which has more options.

**Comment by tboeckmann** [comment]
Editable here: https://coveralls.io/github/mailchain/mailchain/settings

How much coverage decrease is acceptable? 2 options available are:

1. % COVERAGE THRESHOLD FOR FAILURE
1. % COVERAGE DECREASE THRESHOLD FOR FAILURE

**Comment by robdefeo** [comment]
Updated settings as suggested by @tboeckmann, thanks.
