### ISSUE TITLE
Get public key from substrate address

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#269]
**Is your feature request related to a problem? Please describe.**
To support substrate the ability to get the public key from an address SHOULD be supported.

**Describe the solution you'd like**
Determine the public key from address similar to how it is performed in Ethereum

**Describe alternatives you've considered**
N/A

**Additional context**
Need to add

**Comment by robdefeo** [comment]
@tboeckmann You mentioned you found some docs that defined how this was done. Can you add some information to this issue please.

**Comment by tboeckmann** [comment]
See #258

**Comment by robdefeo** [comment]
relates to #282
