### ISSUE TITLE
Endpoint for programmable envelopes

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#278]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2425%20Funded-%2300A156.svg" />](https://issuehunt.io/r/mailchain/mailchain/issues/278)

**Is your feature request related to a problem? Please describe.**
I want to be able to query an endpoint to see the supported envelope types so the client can offer a list of supported envelope types to a user 

**Describe the solution you'd like**

Create an endpoint that returns all available envelopes, that can be used.

- [ ] create `envelopes.go` in `cmd/mailchain/internal/http/handlers`
- [ ] create handler
- [ ] return json response similar to
```
{
    {
        "type": "0x01",
        "description" "Private Message Stored with MLI",
    },
}
```
- [ ] create tests
- [ ] add hander to `cmd/mailchain/internal/http/server.go` use `/envelopes`

**Additional context**

See https://docs.mailchain.xyz/reference/programmable-envelopes for further info on programmable envelopes

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $25.00)

- [<img src='https://avatars1.githubusercontent.com/u/1633235?v=4' alt='robdefeo' width=24 height=24> robdefeo](https://issuehunt.io/u/robdefeo) ($25.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/mailchain/mailchain/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Pancakem** [comment]
Hey @robdefeo. I would like to have a go at this issue.
Just to be sure, I would like to know more about what is required to close the issue.

**Comment by robdefeo** [comment]
Hi @Pancakem currently there are two envelopes, `0x01` and `0x50` however this response should only return `0x01`. The `0x50` was an early version that we are not looking to use going forward. You can create the handler, struct and tests in `cmd/mailchain/internal/http/handlers` and wire it up in `cmd/mailchain/internal/http/server.go` later this function will be extended as more envelopes are added and more details are required. I will assign this issue to you, if you have any questions please ask here or drop me a message in the slack channel. Thanks
