### ISSUE TITLE
Add key asks for a `chain` rather than `protocol`

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#279]
**Describe the bug**

**To Reproduce**
```
Usage:
  mailchain account add [flags]

Flags:
  -C, --chain string         Select the chain [ethereum]
  -h, --help                 help for add
      --passphrase string    Passphrase to encrypt/decrypt key with
  -K, --private-key string   Specify the private key to store

Global Flags:
      --config string         config file (default is $HOME/.mailchain/.mailchain.yaml)
      --empty-passphrase      no passphrase and no prompt
      --key-type string       Select the chain [secp256k1]
      --log-level string      log level [Panic,Fatal,Error,Warn,Info,Debug] (default "warn")
      --prevent-init-config   stop automatically creating config if non is found
```

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.034`

**Expected behavior**
`-C, --chain string         Select the chain [ethereum]` replaced with `-P, --protocol string         Select the protocol [ethereum]`

**Screenshots**
N/A

**Additional context**
Docs also need updating

**Comment by steph-dmts** [comment]
I submitted a PR for this as well as one for updating the docs

**Comment by robdefeo** [comment]
@steph-dmts looks great, I will mege.

**Comment by robdefeo** [comment]
Thanks @steph-dmts for your first contributions to Mailchain, we are super excited that you have created 2 PR's https://github.com/mailchain/mailchain/issues/279 & https://github.com/mailchain/docs.mailchain.xyz/pull/4 as your first contribution 😃
