### ISSUE TITLE
Create a sender service for substrate

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#280]
**Is your feature request related to a problem? Please describe.**
To send messages on substrate, a sender is required.

**Describe the solution you'd like**
substrate sender that implements the `sender.Message` interface
```
type Message interface {
	Send(ctx context.Context, network string, to []byte, from []byte, data []byte, signer signer.Signer, opts SendOpts) (err error)
}
```

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by nikosk686** [comment]
Hi guys, I start looking what is needed for this. You can assign it to me if you want.
