### ISSUE TITLE
API docs show wrong version

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#294]
**Describe the bug**

**To Reproduce**
1. Run `mailchain serve`
1. visit http://127.0.0.1:8080/api/docs
1. See version 0.0.1

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.34`

**Expected behavior**
version should be in line with Mailchain version

**Screenshots**
![image](https://user-images.githubusercontent.com/2022378/65822364-7460eb00-e23a-11e9-9b36-8be6b24671b4.png)

**Comment by robdefeo** [comment]
Ideally the version could be passed when running the `swagger` however this does not appear to be supported. Instead use a placeholder and replace as part of the build step.
