### ISSUE TITLE
Include supported encryption methods when returning public key

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#312]
**Is your feature request related to a problem? Please describe.**
It's not clear what encryption methods are supported for public keys returned.
 
**Describe the solution you'd like**
return a list of available encryption methods with the public key
```
{
    "public_key": "0x369bb60e6d99e30144e8fab8087bd7d171ba7b5dbf691b87319584b3d6c1892c",
    "supported_encryption_types": ["aes256cbc"],
}
```

**Describe alternatives you've considered**
Default by protocol

**Additional context**
N/A

**Comment by Despire** [comment]
@robdefeo can i be assigned to this ? :)

**Comment by Despire** [comment]
This issue can be closed as it's been resolved a while ago.

**Comment by robdefeo** [comment]
Thanks @Despire thats a good spot.
