### ISSUE TITLE
Check private key is valid before returning signer

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#331]
**Is your feature request related to a problem? Please describe.**
With the addition of different public key types, it is possible to create a signer with an incompatible public key

**Describe the solution you'd like**
Check public key type is valid before creating signer, currently it must be `secp256k1`

**Describe alternatives you've considered**
N/A

**Additional context**
`/internal/protocols/ethereum/signer.go` the NewSigner should check key type and return error as needed

**Comment by developerfred** [comment]
@robdefeo I used the verifySignature method but I don't know if this is the best way to do this validation. 
Give me feedback. Thanks  :D

**Comment by robdefeo** [comment]
@developerfred I am not too sure what which method you are referring to I would though suggest look at `crypto/nacl` and you will find 
```
func validatePrivateKeyType(pk crypto.PrivateKey) ([]byte, error) {
	switch pk := pk.(type) {
	case ed25519.PrivateKey, *ed25519.PrivateKey:
		return pk.Bytes()[32:], nil
	default:
		return nil, errors.Errorf("invalid public key type for nacl encryption")
	}
}
```  
it checks for a different key in this case its `secp256k1` but this is a good example.  You can create a similar method in `signer.go` with the accompanying unit tests. I would suggest to return `*ecdsa.PrivateKey, error` then this method can be re-used in the next step

Also in the `func Sign` this check is used again see
```
	pk, ok := e.privateKey.(*secp256k1.PrivateKey)
	if !ok {
		return nil, errors.Errorf("invalid key type")
	}
	ecdsa, err := pk.ECDSA()
	if err != nil {
		return nil, err
	}
```
This could be improved with the new function you are looking at

**Comment by Despire** [comment]
@robdefeo this issue can be closed, as the PR was already merged

**Comment by robdefeo** [comment]
@Despire yes you are correct. Thanks for raising that and your help on this.
