### ISSUE TITLE
Check the private key type used when creating a aes256cbc.NewDecrypter 

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#332]
**Is your feature request related to a problem? Please describe.**
With the addition of different public key types, it is possible to create a signer with an incompatible private key

**Describe the solution you'd like**
Check private key type is valid before creating signer, currently it must be `secp256k1`

**Describe alternatives you've considered**
N/a

**Additional context**
`crypto/cipher/aes256cbc/decrypter.go` NewDecrypter method should check is key is compatible then return error if not

**Comment by olimpias** [comment]
@robdefeo happy new year! May I work on this?

**Comment by tboeckmann** [comment]
Hi @olimpias - sure thing. I've assigned you the issue.
