### ISSUE TITLE
Check if to address matches public key before sending

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#335]
**Is your feature request related to a problem? Please describe.**
Since the change to the way addresses are generated with the addition of the `ed25519` key, there is no check on the address matching the public key when sending a message. 

**Describe the solution you'd like**
In the `isValid` func used by `handlers/SendMessage` check that the to address corresponds to the public key. 

**Describe alternatives you've considered**

**Additional context**
Package `internal/address` contains `FromPublicKey` method, comparing the bytes of the address from this and the to address can be provided.

**Comment by pascaloseko** [comment]
@robdefeo can I take this ticket? I can't assign myself apparently
