### ISSUE TITLE
Add verify method to crypto.PublicKey 

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#347]
**Is your feature request related to a problem? Please describe.**
It is not possible to verify if a `[]byte` is signed by a public key.  This is a problem, when determining the public key from an address and there are multiple different public key possibilities due to the protocol allowing different key types.

**Describe the solution you'd like**
Implement `Verify(message, sig []byte) bool ` on `crypt.PublicKey`. This will mean that the validity of the signed data against all keys that implement this interface, making it trivial to check the validity of signed data with key type / public key.

**Describe alternatives you've considered**
N/A

**Additional context**
Depends on 
- #346 
- #345 
- #327

**Comment by developerfred** [comment]
https://github.com/mailchain/mailchain/pull/412

**Comment by robdefeo** [comment]
closed by #416
