### ISSUE TITLE
unknown status 406: no private key found for address

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#365]
**Describe the bug**
When I run the current `master` branch (at commit [eb02e4e](https://github.com/mailchain/mailchain/commit/eb02e4e79ec7efc518a2158a3e87345d4aa79a8c)) locally, I get the following error:

```
ERRO[2019-11-11T18:04:28Z] unknown status 406: no private key found for address
github.com/mailchain/mailchain/cmd/mailchain/internal/http/handlers.GetMessages.func1
	/Users/tboeckmann/Development/finobo/mailchain/mailchain/cmd/mailchain/internal/http/handlers/messages.go:65
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.13.3/libexec/src/net/http/server.go:2007
github.com/gorilla/mux.(*Router).ServeHTTP
	/Users/tboeckmann/go/pkg/mod/github.com/gorilla/mux@v1.7.1/mux.go:212
github.com/urfave/negroni.Wrap.func1
	/Users/tboeckmann/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46
github.com/urfave/negroni.HandlerFunc.ServeHTTP
	/Users/tboeckmann/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
	/Users/tboeckmann/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/rs/cors.(*Cors).ServeHTTP
	/Users/tboeckmann/go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:240
github.com/urfave/negroni.middleware.ServeHTTP
	/Users/tboeckmann/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/urfave/negroni.(*Negroni).ServeHTTP
	/Users/tboeckmann/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96
net/http.serverHandler.ServeHTTP
	/usr/local/Cellar/go/1.13.3/libexec/src/net/http/server.go:2802
net/http.(*conn).serve
	/usr/local/Cellar/go/1.13.3/libexec/src/net/http/server.go:1890
runtime.goexit
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/asm_amd64.s:1357 
```
**To Reproduce**
1. Clone latest version of `master` 
1. Add an account `go run cmd/mailchain/main.go account add --protocol=ethereum --private-key=PRIVATE_KEY --key-type="secp256k1"`
    Note: `go run cmd/mailchain/main.go account add --protocol=ethereum --private-key=PRIVATE_KEY` gives `Error: `key-type` must be specified`. This feels strange!
1. Run `go run cmd/mailchain/main.go serve`
1. In browser, navigate to: https://inbox-staging.mailchain.xyz/#/ (this version has a workaround for protocol and network params)
1. See error in terminal or browser developer console: `unknown status 406: no private key found for address`

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: vdev`
Currently at commit: [eb02e4e](https://github.com/mailchain/mailchain/commit/eb02e4e79ec7efc518a2158a3e87345d4aa79a8c)

**Expected behavior**
This error should not appear. It may be related to `key-type` in account add, where key is stored in different format.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6  
 - Browser [brave/ chrome]

**Additional context**

**Comment by robdefeo** [comment]
The new version of the keystore was using the old method of looking for an address which is caused this confusing bug. Some users may of not noticed if they added the same key with old and new method.
