### ISSUE TITLE
cipher/nacl does not include the encryption method in the encrypted data.

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#366]
**Is your feature request related to a problem? Please describe.**
The encrypted data must indicated what encrypted method was used. Mailchain allows multiple encryption methods, the first byte of encrypted data is used to select the correct encryption protocol. This byte is not set in `cypto/cipher/nacl`.

**Describe the solution you'd like**

- [ ] After encrypting data with `easySeal` the result must have `ciper.NACL` prepended.
- [ ] Before decrypting data check the encrypted data has `ciper.NACL` as the first byte.
- [ ] Before decrypting data remove the first byte if `ciper.NACL` then pass to `easyOpen`
- [ ] Handle `nil` or `[]byte{}` inputs for `Decrypt` method
- [ ] Add test cases

**Additional context**

`cipher/aes256cbc` has this an implementation of this

**Comment by u5surf** [comment]
@robdefeo 
Also,I will catch this issue

**Comment by robdefeo** [comment]
Thanks @u5surf :) let me know if you need anything
