### ISSUE TITLE
cipher/noop does not include the encryption method in the encrypted data.

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#367]
**Is your feature request related to a problem? Please describe.**
The encrypted data must indicated what encrypted method was used. Mailchain allows multiple encryption methods, the first byte of encrypted data is used to select the correct encryption protocol. This byte is not set in `cypto/cipher/noop`. Although this encryption method does not actually perform encryption or decryption as it is a "no operation" implementation it still must indicated its method.

**Describe the solution you'd like**

- [ ] After "encrypting" data the result must have `ciper.NoOperation` prepended.
- [ ] Before "decrypting" data check the encrypted data has `ciper.NoOperation` as the first byte.
- [ ] Before "decrypting" data remove the first byte if `ciper.NoOperation`.
- [ ] Handle `nil` or `[]byte{}` inputs for `Decrypt` method
- [ ] Add test cases

**Additional context**

`cipher/aes256cbc` has this an implementation of this.

**Comment by u5surf** [comment]
@robdefeo 
Hi, I wanna be catching this issue.
