### ISSUE TITLE
Include curve-type when returning public key

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#381]
**Is your feature request related to a problem? Please describe.**
A public key can be of different types, `secp256k1`, `ed25519`, `sr25519`, with the addition of `substrate` to send a message it will need to know what `curve-type` is used to be able to decode it ref #52 

**Describe the solution you'd like**
- [ ] Including the key type of the found public key
```
{
    "public_key": "0x369bb60e6d99e30144e8fab8087bd7d171ba7b5dbf691b87319584b3d6c1892c"
    "curve-type": "secp256k1"
}
```
- [ ] use new return value `crypto.PublicKey` created by #414
- [ ] use `Kind` created by #382

**Comment by abadojack** [comment]
@robdefeo Can I have this assigned to me?

**Comment by robdefeo** [comment]
Assigned :) Thanks @abadojack
