### ISSUE TITLE
API Docs: PutRead is unclear in docs

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#388]
**Describe the bug**
The docs are not accurate/ not clear:

> ## Put inputs.
> Put encrypted input of all mailchain messages.

http://127.0.0.1:8080/api/docs#operation/PutRead

**To Reproduce**
1. Run the mailchain client
1. http://127.0.0.1:8080/api/docs#operation/PutRead

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.37`

**Expected behavior**

It should say:
> ## PutRead
> Mark message as read

**Screenshots**
![image](https://user-images.githubusercontent.com/2022378/68999614-b6adbc80-08ba-11ea-8636-5cac8c467b5c.png)

**Comment by rickynyairo** [comment]
Hi @tboeckmann , I'd like to be assigned this issue

**Comment by tboeckmann** [comment]
@rickynyairo thanks for taking a look

**Comment by robdefeo** [comment]
closed by #399
