### ISSUE TITLE
Add `EncodeBase58` method

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#394]
**Is your feature request related to a problem? Please describe.**
It is not clear what method to use to encode `[]byte` to `base58` strings

**Describe the solution you'd like**
- [ ] create `EncodeBase58` in `internal/encoding`
- [ ] use `"github.com/mr-tron/base58"` package
- [ ] call `base58.Encode`

**Comment by developerfred** [comment]
- [ ]  create EncodeBase58 in internal/encoding
- [ ] use "github.com/mr-tron/base58" package
- [ ] call base58.Encode

task done

**Comment by robdefeo** [comment]
closed by #397
