### ISSUE TITLE
encoding.EncodeZeroX should not return encoding type

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#395]
**Is your feature request related to a problem? Please describe.**
`encoding.EncodeZeroX` returns the encoding type used, this makes the method more difficult to use.

**Describe the solution you'd like**
- [ ] change method signature to `EncodeZeroX(src []byte) (encoded string)`
- [ ] update method docs
- [ ] change methods where it is used

**Comment by epishovska** [comment]
@robdefeo Can I have this assigned to me?

**Comment by robdefeo** [comment]
fixed by #402
