### ISSUE TITLE
Infer key type from public key and private key bytes

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#403]
**Is your feature request related to a problem? Please describe.**
Mailchain requires private keys to, decrypt and sign transactions. To add a private key to mailchain the used needs to include the private key and key type. It is not expected that users understand what key type they have.
While ethereum and other protocols support a single key type, substrate supports, `ed25519`, `sr25519`, and `secp256k1`.

**Describe the solution you'd like**
Create a method that can determine the key type from the public and private key bytes combination.

- [ ] create method in `crypto/multikey`
- [ ] method signature `GetKeyKindFromBytes(publicKey []byte, privateKey []byte) (crypto.PrivateKey, error)`
- [ ] check each key type to see if the private and public keys match
  - [ ] create `PrivateKey` from `[]byte`
  - [ ] compare output of `.Bytes()` to `publicKey []byte`
- [ ] check all candidate key types
- [ ] if a single match return `crypto.PrivateKey` for the matching key type
- [ ] use `"github.com/mailchain/mailchain/crypto"` package
- [ ] no match return error
- [ ] multiple match return inconsistent/inconclusive error

**Additional context**
More key types will be added in the future

**Comment by asnimansari** [comment]
@tboeckmann Shall I do this?

**Comment by asnimansari** [comment]
Shall I do this ?

**Comment by olimpias** [comment]
Hi @robdefeo, could you assign the task to me? Thanks!

**Comment by robdefeo** [comment]
closed by #535
