### ISSUE TITLE
HTML Detection Fails on Send Message

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#406]
**Describe the bug**
When I send a message with an HTML body, it appears mailchain is appending the following `/r/n`
```
"body":"<h2>Heading 1</h2><h3>Heading 2</h3><h4>Heading 3</h4><p>Paragraph</p><p>Some bold text: <strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.</strong></p><p>Some italic text: <i>Lorem ipsum dolor sit amet consectetur adipisicing elit.</i></p><p>Some linked text: Lorem ipsum dolor sit amet consectetur adipisicing elit.</p><p>3 Bullets:</p><ul><li>Lorem</li><li>ipsum dolor sit</li><li>amet consectetur adipisicing elit.</li></ul><p>3 numbers:</p><ol><li>Lorem</li><li>ipsum dolor sit</li><li>amet consectetur adipisicing elit.</li></ol><blockquote><p>Quoted text: Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.</p></blockquote><p>&nbsp;</p><p><strong>Table</strong>:</p><figure class=\"table\"><table><tbody><tr><td>Row1</td><td>col2</td><td>col3</td></tr><tr><td>Row2</td><td>col2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.&nbsp;</td><td>col3</td></tr><tr><td>Row3</td><td>col2</td><td>col3</td></tr></tbody></table></figure>"
```
**To Reproduce**
The following curl request fails.Update the right send for an address you control.

```
curl 'http://127.0.0.1:8080/api/messages?protocol=ethereum&network=ropsten' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Origin: http://localhost:4200' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Referer: http://127.0.0.1:8080/' \
  -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  --data-binary '{"message":{"body":"<h2>Heading 1</h2><h3>Heading 2</h3><h4>Heading 3</h4><p>Paragraph</p><p>Some bold text: <strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.</strong></p><p>Some italic text: <i>Lorem ipsum dolor sit amet consectetur adipisicing elit.</i></p><p>Some linked text: Lorem ipsum dolor sit amet consectetur adipisicing elit.</p><p>3 Bullets:</p><ul><li>Lorem</li><li>ipsum dolor sit</li><li>amet consectetur adipisicing elit.</li></ul><p>3 numbers:</p><ol><li>Lorem</li><li>ipsum dolor sit</li><li>amet consectetur adipisicing elit.</li></ol><blockquote><p>Quoted text: Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.</p></blockquote><p>&nbsp;</p><p><strong>Table</strong>:</p><figure class=\"table\"><table><tbody><tr><td>Row1</td><td>col2</td><td>col3</td></tr><tr><td>Row2</td><td>col2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.&nbsp;</td><td>col3</td></tr><tr><td>Row3</td><td>col2</td><td>col3</td></tr></tbody></table></figure>","headers":{"from":"0x92d8f10248c6a3953cc3692a894655ad05d61efb","reply-to":"0x92d8f10248c6a3953cc3692a894655ad05d61efb","to":"0xd5ab4ce3605cd590db609b6b5c8901fdb2ef7fe6"},"public-key":"0x69d908510e355beb1d5bf2df8129e5b6401e1969891e8016a0b2300739bbb00687055e5924a2fd8dd35f069dc14d8147aa11c1f7e2f271573487e1beeb2be9d0","subject":"html 5"}}' \
  --compressed
  
```

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.1.0`

**Expected behavior**
The `/r/n` should not be appended, which will make the `"content-type": "text/plain; charset=\"UTF-8\""` come back as `"content-type": "text/html; charset=\"UTF-8\""`

**Screenshots**
![image](https://user-images.githubusercontent.com/2022378/69479336-f5c89a00-0df3-11ea-99fc-4f1f37ca33bb.png)

**Desktop (please complete the following information):**
 - Version 0.0.37

**Comment by robdefeo** [comment]
I would suggest writing an extra test case for this issue and then working through the problem.

**Comment by nikosk686** [comment]
Hi @tboeckmann. The problem here is not the `\r\n`. It is added when fetching the messages for the mailchain client, but it does not get appended when the message is being sent, where the type format detection takes places.
The problem is that `http.DetectContentType(string)` seems to have poor implementation. It does not recognize other header than `<h1>` (if you replace h2 with h1 in your message you'll see that it is detected as /text/html) and also it seems to recognize as html only parts of texts that begin with a tag.
For example,
`<p>This</p> gets detected`
`but not <p>this</p>`
When I initially implemented this functionality I added small html bodies in my tests so I did not realize the poor performance.
Maybe we should reconsider the way mailchain detects the format of messages.

**Comment by robdefeo** [comment]
Thanks @nikosk686 this is very helpful. I would suggest the following implementation:

- [ ] add `Content-Type   string `json:"content-type"`` to PostRequestBody
- [ ] document new header field including allowed values
- [ ] check for either `text/plain; charset=\"UTF-8\"` or `text/html; charset=\"UTF-8\"`
- [ ] remove `detectContentType` in `internal/mail/message.go`
- [ ] required `contentType` for `NewMessage` in `internal/mail/message.go`
- [ ] update references
- [ ] update and create tests

**Comment by nikosk686** [comment]
Hi guys,
I applied a pr for this.
@tboeckmann client now should contain `content-type` with one of the follwing values
`'text/plain; charset=\"UTF-8\"', 'text/html; charset=\"UTF-8\"'`

In case that's missing or value is invalid it defaults to `'text/plain; charset=\"UTF-8\"`.
@robdefeo as you can see I made this optional with default instead of mandatory with error on missing or invalid value.
The alternative should be simple if is preferred.

**Comment by robdefeo** [comment]
@nikosk686 sounds great, I left a small review to your PR. Looking forward to getting this merge. I like the approach you have taken
