### ISSUE TITLE
etherscan.getFromResultHash unit tests

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#408]
**Is your feature request related to a problem? Please describe.**
Etherscan has low test coverage making it more difficult to maintain in the future.

**Describe the solution you'd like**
- [ ] Create unit tests file `internal/clients/etherscan/pubkey-finder.go`
- [ ] Create unit test for `getFromResultHash`

**Comment by catacioba** [comment]
I would like to work on this
