### ISSUE TITLE
Create DecodeHex and EncodeHex methods

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#409]
**Is your feature request related to a problem? Please describe.**
Its not clear what method exists to encode or decode plain hex

**Describe the solution you'd like**

- [ ] use `internal/encoding` package
- [ ] Create `EncodeHex` call to `encoding/hex` package
- [ ] Create `DecodeHex` call to `encoding/hex` package
- [ ] Create docs for `EncodeHex`
- [ ] Create docs for `DecodeHex`
- [ ] create tests
- [ ] create `MustDecodeHex` in `internal/encoding/encodingtest` package

**Comment by developerfred** [comment]
- [x] use internal/encoding package
- [x] Create EncodeHex call to encoding/hex package
- [x] Create DecodeHex call to encoding/hex package
- [x] Create docs for EncodeHex
- [x] Create docs for DecodeHex
- [x] create tests
- [x] create MustDecodeHex in internal/encoding/encodingtest package
- [x] change testutil to encodingtest.MustDecodeHex
