### ISSUE TITLE
Infer key type from signature and public key bytes

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#413]
**Is your feature request related to a problem? Please describe.**
Mailchain requires public keys to, encrypt messages and calculate the address. While ethereum and other protocols support a single key type, substrate supports, `ed25519`, `sr25519`, and `secp256k1`. To reliably determine a public key type the key type must be tested.

**Describe the solution you'd like**
Create a method that can determine the key type from the public and private key bytes combination.

- [ ] create method in `crypto/multikey`
- [ ] method signature `GetKeyKindFromSignature(publicKey, message, sig []byte, keyTypes []???) (crypto.PublicKey, error)`
- [ ] `keyTypes []string` or `keyTypes []crypto.PublicKey`?
- [ ] check each key type to see if signature, message, and public key combination is valid
  - [ ] create `PublicKey` from `[]byte`
  - [ ] check output of `.Verify()`
- [ ] check all candidate key types
- [ ] if a single match return `crypto.PublicKey`
- [ ] no match return error
- [ ] multiple match return inconsistent/inconclusive error

**Additional context**

- Not all protocols have this requirement. 
- More key types will be added in the future

**Comment by robdefeo** [comment]
@Despire this might be an interesting one for you once #345 is completed?

**Comment by Despire** [comment]
Looks interesting ! :)
you can assign me and once #345 is ready I'll start.

**Comment by Despire** [comment]
This issue can be closed :) @robdefeo
