### ISSUE TITLE
finder.PublicKeyFromAddress should return PublicKey

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#414]
**Is your feature request related to a problem? Please describe.**
The key of key is needed to return what encryption methods are allowed

**Describe the solution you'd like**
Extend public key finder to return PublicKey

- [ ] In `internal/mailbox/pubkey.go` change `PublicKeyFromAddress(ctx context.Context, protocol, network string, address []byte) ([]byte, error)` to `PublicKeyFromAddress(ctx context.Context, protocol, network string, address []byte) (cypto.PublicKey, error)`
- [ ] use `"github.com/mailchain/mailchain/crypto"` package
- [ ] change `internal/clients/etherscan/pubkey-finder.go` to new signature. Use `secpk256k1` package for `PublicKey`
- [ ] change `internal/protocols/substrate/pubkey.go` to new signature. Use `ed25519` package for `PublicKey`
- [ ] run `make generate` to update mock
- [ ] update tests

**Additional context**
Substrate will be extended in the future to support different key types

**Comment by epishovska** [comment]
@robdefeo Can I have this assigned to me?
