### ISSUE TITLE
Create badgerdb as a state store

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#425]
**Is your feature request related to a problem? Please describe.**
https://github.com/dgraph-io/badger/ gives 

**Describe the solution you'd like**
Implement the state store with Badger BD this should be feature parity with `stores/ldbstore`

- [ ] use BadgerDB v2.0.0 or above
- [ ] Implement `State` interface from `stores/state.go`
- [ ] create unit tests

**Additional context**
Transactions are useful for creating secondary indexes in the future.

**Comment by Despire** [comment]
Anybody working on this ?

**Comment by robdefeo** [comment]
No. @Despire are you interested to pick this up?

**Comment by Despire** [comment]
@robdefeo yes
