### ISSUE TITLE
Prevent No Operation encrypter from being used in 0x01 envelope

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#428]
**Is your feature request related to a problem? Please describe.**
The original intention for 0x01 envelope was to send encrypted messages. 0x01 does not do any checking on the encrypter being used, this means that NoOperation encrypter can be used to store the data in unencrypted format.

**Describe the solution you'd like**

Check the encrypter used when creating a ZeroX1 envelope.

- [ ] return error if `noop.Encrypter` is supplied to `NewZeroX01`
- [ ] create tests

**Comment by u5surf** [comment]
@robdefeo 
Hi, I’m interested in this issue.
 I think the first of all, each encryptor should have the function which returns the cipher type itself. It can be indicate cipher type inside `NewZeroX10.` I can implement it.

**Comment by robdefeo** [comment]
@u5surf thanks for picking this up. I am not entirely sure what you mean by your suggestion. Can you expand you thinking or provide a bit or sudo code?

**Comment by robdefeo** [comment]
Hi @u5surf thanks for offering to pick up this issue and create a pull request. I see there has not been any activity for a while. If you have made any progress or have a PR nearly finish please let me know.  In the meanwhile I am going to unassign you and open the issue up to the community again.

**Comment by marianososto** [comment]
Hi, I've created PR #754  for this ISSUE.

**Comment by robdefeo** [comment]
Thanks @marianososto, the PR looks good. 👍 Closing based on that.
