### ISSUE TITLE
Rename DecodeZeroX and EncodeZeroX to include hex

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#429]
**Is your feature request related to a problem? Please describe.**
Its not clear what encoding method `DecodeZeroX` and `EncodeZeroX` use

**Describe the solution you'd like**

- [ ] rename `EncodeZeroX` to `EncodeHexZeroX`
- [ ] update docs for `EncodeHexZeroX`
- [ ] rename `DecodeZeroX` to `DecodeHexZeroX`
- [ ] update docs for `DecodeHexZeroX`
- [ ] update all function usage references
- [ ] rename tests

**Comment by developerfred** [comment]
https://github.com/mailchain/mailchain/pull/430 done
