### ISSUE TITLE
/api/messages now returns `null` instead of `[]`

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#434]
**Describe the bug**
When I query the messages endpoint with an address that has no messages, the response returns `null`.

e.g. 
```
http://127.0.0.1:8080/api/messages?protocol=ethereum&network=mainnet&address=0x5b47f32590ca2d63d3b4cfec4a9f88aaa824d9e0
```
returns
```
{"messages":null}
```

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: dev@c85056b`

**Expected behavior**
It should return an empty array: `{"messages":[] }`

**Comment by developerfred** [comment]
I believe we need an empty return error handling and a new test for this case.
