### ISSUE TITLE
remove secp256k1.PublicKeyFromHex method

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#435]
**Is your feature request related to a problem? Please describe.**
The calling to `secp256k1.PublicKeyFromHex` was removed by method and tests still exist, this should be removed as `PublicKeyFromBytes` is the prefered approach.

**Describe the solution you'd like**
- [ ] remove `secp256k1.PublicKeyFromHex` method
- [ ] remove tests

**Comment by odedpriva** [comment]
I updated the code but now the golangci-lint ( runs as pre-commit hookl ) complains about code that is unrelated to the change I have made. 

What should I do ? 

p.s, this is my first PR.

**Comment by developerfred** [comment]
Do the ```golanci-lint run``` only on the package you made change.

sample:
```golanci-lint run crypto/secp256k1```
