### ISSUE TITLE
chore: move generic settings packages

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#471]
**Is your feature request related to a problem? Please describe.**
`settings` package is currently under `cmd/mailchain` some of the package would be useful in other cmds

**Describe the solution you'd like**
Move these packages to root package `cmd/internal/settings`
- [ ] `cmd/mailchain/internal/settings/output`
- [ ] `cmd/mailchain/internal/settings/values`

**Comment by developerfred** [comment]
* [x]  `cmd/mailchain/internal/settings/output`
 * [x]  `cmd/mailchain/internal/settings/values`
