### ISSUE TITLE
nacl encrypter does not encrypt messages correctly

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#482]
**Is your feature request related to a problem? Please describe.**
`crypto/cipher/nacl` uses `SecretBox` which is for symmetric encryption, this means that the implementation is incorrect it should of used `Box`. `nacl.Box` does not support `ed25519` and `sr25519` only `x25519` so can not be used.

**Describe the solution you'd like**

Currently nacl is not used in to send any messages so it can safely be removed.

- [ ] remove `crypto/cipher/nacl`
- [ ] remove all references to `crypto/cipher/nacl`
- [ ] remove `NACL byte = 0x2a` from `crypto/cipher/cipher.go`
- [ ] remove all references to `ciper.NACL`

**Comment by developerfred** [comment]
> * remove `crypto/cipher/nacl`
> * [x]  remove all references to `crypto/cipher/nacl`
> * [x]  remove `NACL byte = 0x2a` from `crypto/cipher/cipher.go`
> * [x]  remove all references to `ciper.NACL`

**Comment by robdefeo** [comment]
With the key exchange interface #497 and implementations in secp256k1 #501 , ed25519 #504, and 
sr25519 #505 and fix #528 it is now possible to the ECHD keys exchange for these key types and generate a shared secret which can be used with secretbox.
