### ISSUE TITLE
create generic errors for cipher encrypt and decrypt

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#498]
**Is your feature request related to a problem? Please describe.**
When failing to decrypt or encrypt a generic error should be returned to prevent any extra information from being returned.

**Describe the solution you'd like**
- [ ] `errors.go` in `crypto/cipher`
- [ ] create `ErrEncrypt = errors.New("cipher: encryption failed")`
- [ ] create `ErrDecrypt = errors.New("cipher: decryption failed")`
- [ ] add comments to  `ErrEncrypt` and `ErrDecrypt`

**Comment by developerfred** [comment]
>     * [x]  `errors.go` in `crypto/cipher`
> 
>     * [x]  create `ErrEncrypt = errors.New("cipher: encryption failed")`
> 
>     * [x]  create `ErrDecrypt = errors.New("cipher: decryption failed")`
> 
>     * [x]  add comments to  `ErrEncrypt` and `ErrDecrypt`

**Comment by robdefeo** [comment]
closed by #508
