### ISSUE TITLE
Simpler way to generate secp256k1.ECIES()

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#502]
**Is your feature request related to a problem? Please describe.**
`secp256k1.ECIES()` first gets the public key bytes then converts them to an `ecdsa.PublicKey` then uses this to generate a `ecies.PublicKey`. The first step is not needed as `pk.ecdsa` is already an `ecdsa.PublicKey`

**Describe the solution you'd like**
- [ ] replace `ECIES() (*ecies.PublicKey, error)` with `return ecies.ImportECDSAPublic(&pk.ecdsa), nil`
- [ ] investigate if `ECIES() (*ecies.PublicKey, error)` should be replaced with `ECIES() *ecies.PublicKey` or if `ecdsa ecdsa.PublicKey` should be `ecdsa 7ecdsa.PublicKey` and nil value check.
- [ ] run `go test ./...`

**Comment by developerfred** [comment]
- [x] replace ECIES() (*ecies.PublicKey, error) with return ecies.ImportECDSAPublic(&pk.ecdsa), nil

- [x] investigate if ECIES() (*ecies.PublicKey, error) should be replaced with ECIES() *ecies.PublicKey or if ecdsa ecdsa.PublicKey should be ecdsa 7ecdsa.PublicKey and nil value check.

- [x] run go test ./...
