### ISSUE TITLE
implement datastore.RawTransactionStore using AWS S3

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#522]
**Is your feature request related to a problem? Please describe.**
The indexer needs to store raw transactions incase they need to be processed later

**Describe the solution you'd like**

- [ ] Create in `cmd/indexer/internal/datastore/s3`
- [ ] Use `github.com/aws/aws-sdk-go/service/s3` to interact with S3 ref `stores/s3store/sent.go`
- [ ] Implement `datastore.RawTransactionStore` from `cmd/indexer/internal/datastore/transaction.go`
- [ ] create unit tests see ref `stores/s3store/sent_test.go`

**Comment by olimpias** [comment]
@robdefeo, you can assign to me. :)

**Comment by robdefeo** [comment]
This should be a useful link to help with unit testing https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3iface/

**Comment by olimpias** [comment]
@robdefeo , is something left TODO for this task? Could we close it?

**Comment by robdefeo** [comment]
@olimpias this is completed by your pull request #550 but was not closed. Will get that sorted now. Thanks :)
