### ISSUE TITLE
Create local cache of messages

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#543]
**Is your feature request related to a problem? Please describe.**
When reading messages Mailchain checks the remote sent store for every API call. This is inefficient, prevents the recipient easily preserving the messages, and requires an internet connection.

**Describe the solution you'd like**
- [ ] Check message cache before checking message location `GetMessage` in `stores/get.go`
- [ ] After getting a valid message body store in cache
- [ ] use `locHash, _:= hash.Create(hash.SHA3256, []byte(location)])` and `encoding.EncodeHex(locHash)` as cache key
- [ ] It should be a Read through cache
- [ ] Use `github.com/spf13/afero` to interact with filesytem for cache store
- [ ] Store messages in original format
- [ ] create interface for cache and pass as a value to `GetMessage`

**Comment by olimpias** [comment]
Hi @robdefeo , may I work on this?

**Comment by robdefeo** [comment]
Hi @olimpias yes absolutely I took a recent look at this and have updated the issue to with a bit more detail. Any questions just reach out. I'll assign this to you now

**Comment by olimpias** [comment]
Hi @robdefeo , should I define a setting for cache time? LIke `MailboxState` struct in settings package. I observe that we are reading configurations from a yaml file. I guess its worth to add caching time there as well. What do you think? Or I can make it hardcoded for now and I can create a separate MR for this purpose.

**Comment by robdefeo** [comment]
closed by #613
