### ISSUE TITLE
create extrinsic processor for cmd/indexer/internal/substrate

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#553]
**Is your feature request related to a problem? Please describe.**
`cmd/indexer` needs to process all extrinsics in a substrate block

**Describe the solution you'd like**
- [ ] create `transaction.go` in `cmd/indexer/internal/substrate`
- [ ] implement `Transaction` from `cmd/indexer/internal/actions/transaction.go` see `cmd/indexer/internal/ethereum/transaction.go`
- [ ] create tests

**Comment by developerfred** [comment]
Hi @robdefeo add me to this issue.

**Comment by developerfred** [comment]
Thanks!

**Comment by robdefeo** [comment]
@developerfred I am going to un assign this there has not been an update in a while. Let me know if there are any other issues you want to look at.

**Comment by robdefeo** [comment]
closed by #604
