### ISSUE TITLE
create block processor for cmd/indexer/internal/substrate

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#554]
**Is your feature request related to a problem? Please describe.**
`cmd/indexer` needs to process all block in a substrate chain

**Describe the solution you'd like**
- [ ] create `block.go` in `cmd/indexer/internal/substrate`
- [ ] implement `Block` from `cmd/indexer/internal/actions/block.go` see `cmd/indexer/internal/ethereum/block.go`
- [ ] create tests

**Comment by Despire** [comment]
Hey, I can help you out with this.

**Comment by robdefeo** [comment]
closed by #578
