### ISSUE TITLE
Add get latest to BlockByNumber

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#556]
**Is your feature request related to a problem? Please describe.**
Sequential indexers need to know when the end of the blockchain has been reached.

**Describe the solution you'd like**
- [ ] Add `LatestBlockNumber(ctx context.Context) (uint64, err error)` method to `BlockByNumber` interface in `cmd/indexer/internal/clients/block.go` 
- [ ] Rename method from `Get` to `BlockByNumber`
- [ ] Rename interface from `BlockByNumber` to `Block`
- [ ] Rename method from `Get` to `BlockByNumber` in `cmd/indexer/internal/ethereum/client.go` 
- [ ] Add `GetLatest(ctx context.Context) (blk interface{}, err error)` to `cmd/indexer/internal/ethereum/client.go` 
- [ ] Add tests
- [ ] Run `go generate ./...` to update mock for interface

**Comment by rickynyairo** [comment]
Hi, I'd like to work on this.
