### ISSUE TITLE
bug: Address is returned incorrectly by /nameservice/name/.../resolve endpoint

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#595]
**Describe the bug**

When I try to resolve an unregistered ENS name that has its resolver set to `0x0000000000000000000000000000000000000000`, the response from the API is:

```
{"address":"0x","status":0}
```

If this reducing down the zeros (i.e. handling it as a number)? Or something else?

**To Reproduce**
1. Run `mailchain serve`
2. Browse to `http://127.0.0.1:8080/api/nameservice/name/alf.eth/resolve?protocol=ethereum&network=mainnet`

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.48`

**Expected behavior**
It should return:

```
{"address":"0x0000000000000000000000000000000000000000","status":0}
```

**Comment by robdefeo** [comment]
When testing out the `nameservice` locally it returns the expected response 200 `{"address":"","status":3}` e.g. `Non-Existent Domain`. Will look in to the `mailchain` api layer

**Comment by robdefeo** [comment]
Looking more in depth the correct response from http://127.0.0.1:8080/api/nameservice/name/alf.eth/resolve?protocol=ethereum&network=mainnet should be `{"address":"","status":3}` This will describe the result correctly. The status code was previously not being passed from the `nameservice`
