### ISSUE TITLE
Bug: /messages call fails with error from etherscan (endpoint has changed)

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#627]
**Describe the bug**
When I call the messages endpoint, I receive an error:
**Endpoint:**
```
http://127.0.0.1:8080/api/messages?protocol=ethereum&network=mainnet&address=0x92d8f10248c6a3953cc3692a894655ad05d61efb`
```

**Error:**
```
{"code":500,"message":"Get https://etherscan.io/api?action=txlist\u0026address=0x92D8f10248C6a3953CC3692A894655ad05D61Efb\u0026endblock=99999999\u0026module=account\u0026sort=desc\u0026startblock=0: auto redirect is disabled"}
```

Then, when calling the etherscan url (replacing `\u0026` with `&`):
```
https://etherscan.io/api?action=txlist&address=0x92D8f10248C6a3953CC3692A894655ad05D61Efb&endblock=99999999&module=account&sort=desc&startblock=0
```
returns error: 
```
{"status":"0","message":"NOTOK","result":"Invalid API URL endpoint, use api.etherscan.io"}
```

**To Reproduce**
1. Configure Mailchain with at least one Ethereum address
1. Go to 'https://inbox.mailchain.xyz/#/'
2. Inspect the developer console
3. See failed message endpoint call

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.60`

**Expected behavior**
It should fetch messages

**Additional context**

**Comment by robdefeo** [comment]
closed by #639
