### ISSUE TITLE
status 500: open ˜/.mailchain/.keystore: no such file or directory

### ISSUE THREAD

**Issue by acpsjr** [mailchain/mailchain#644]
**Describe the bug**
Mailchain serve command returns status 500: open ˜/.mailchain/.keystore: no such file or directory
Unable to send or receive messages via inbox.mailchain.xyz
**To Reproduce**
1. Go to terminal
2. Type mailchain serve
3. Scroll down to ERROR message in red
4. See error: status 500: open ˜/.mailchain/.keystore: no such file or directory

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.66`

**Expected behavior**
Without errors, the web application inbox.mailchain.xyz should work.

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser Chrome
 - Version 86.0.4240.80 (Official Build) (x86_64)

**Additional context**
Mailchain was installed o
<img width="1190" alt="Screen Shot 2020-10-21 at 3 52 06 PM" src="https://user-images.githubusercontent.com/73237568/96729870-e829e480-13b5-11eb-9e18-83ac08223993.png">
n a Mac with Homebrew  and keys were created using Etherscan and Pinata.

**Comment by tboeckmann** [comment]
Hi @acpsjr - thanks for raising this issue.

Did you run the `account add` command (see https://docs.mailchain.xyz/ethereum-instructions/setting-up)?

**Comment by acpsjr** [comment]
Hi @tboeckmann - thank you for your support. I missed that step. I am sorry about that. It is working now. Thanks again for your help. Have a great day!
