### ISSUE TITLE
Sending message fails: 401 Unauthorized response

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#645]
**Describe the bug**
When sending a message on Ethereum Mainnet, the inbox returns the following error:

could not send message: could not send transaction: could not determine chain id: 401 Unauthorized: {"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Must be authenticated!"}}

```
{"message":{"body":"<p>Exciting news. How's it going?</p>","headers":{"from":"0x123...567","reply-to":"0x123...567","to":"0x123...567"},"public-key":"0xxxxx","public-key-encoding":"hex/0x-prefix","public-key-kind":"secp256k1","subject":"Eth 2 launched"},"envelope":"0x01","encryption-method-name":"aes256cbc","content-type":"text/html; charset=\"UTF-8\""}
```

**Errors in terminal:**
could not determine chain id
could not send transaction
could not send message 

Appears to be linked to this: https://docs.alchemyapi.io/documentation/error-reference

**To Reproduce**

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.66`

**Expected behavior**
The message should have sent

**Desktop (please complete the following information):**
 - Browser [Brave]
 - Inbox version: 0.0.15

**Comment by robdefeo** [comment]
Latest version of `cmd/relay` deployed to https://relay.mailchain.xyz/ this has resolved the error
