### ISSUE TITLE
Windows configuration - Application setup issue

### ISSUE THREAD

**Issue by sa3664** [mailchain/mailchain#705]
**Describe the bug**
I am receiving the below error while doing the application setup in my local windows system :

Error: Could not config mailbox store: During db.vlog.open: Value log truncate required to run DB. This might result in data loss

**To Reproduce**
1. Go to 'https://github.com/mailchain/mailchain/blob/master/DEVELOPMENT_GUIDE.md'
2. Go to "Add account" and run "go run cmd/mailchain/main.go account add --protocol=ethereum --key-type="secp256k1" --private-key=YOUR_PRIVATE_KEY". 
3.  After adding an account, scroll down to "Serve" and run "go run cmd/mailchain/main.go serve". 

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version:  v0.0.69`

**Expected behavior**
The expected behavior should be a running instance of mailchain application in local.

**Screenshots**
![image](https://user-images.githubusercontent.com/57690238/111884349-918dfa00-8997-11eb-812a-e95ffde0501b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
N/A

**Comment by robdefeo** [comment]
Hi @sa3664 can you take a look at PR #707 and see if this fix resolves the issue you were having

**Comment by sa3664** [comment]
Hello @robdefeo I tried the fix from  PR #707 , however, was receiving the below error on two different windows machines :

![image](https://user-images.githubusercontent.com/57690238/112077691-66e8a080-8b53-11eb-91aa-71f289c9398c.png)

Upon researching, I found a recommendation on the official badger GitHub repo on the below link  :

https://github.com/dgraph-io/badger/issues/246

The working solution is available in PR #708
