### ISSUE TITLE
Return balance of address via API

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#713]
**Is your feature request related to a problem? Please describe.**
In order to show users their current balance in the inbox, we need an endpoint that returns the users current (available to spend) balance in the context of a protocol and network.

**Describe the solution you'd like**
GET `/addresses/{address}/balance?protocol=ethereum&network=ropsten` returns:
```
{
  "balance": 2183846200000000000,
  "unit": "wei"
}
```

**Ethereum**
See `eth_getBalance` [here](https://eth.wiki/json-rpc/API)
Returns current balance in wei

**Edgeware**
E.g. see `balance_status` [here](https://github.com/centrifuge/go-substrate-rpc-client/blob/3b7101e22320e6f4ec38c3edfdc5e98408cb9b8c/types/balance_status.go)

**Comment by sa3664** [comment]
@tboeckmann  Could you please assign this to me.
